-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.match
(
    id serial NOT NULL,
    format text COLLATE pg_catalog."default",
    date timestamp without time zone,
    tournament_id integer,
    tournament_type text COLLATE pg_catalog."default",
    finished boolean DEFAULT false,
    CONSTRAINT match_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.match_participants
(
    match_id integer NOT NULL,
    player_profile_id integer NOT NULL,
    score integer DEFAULT 0,
    CONSTRAINT match_participants_pkey PRIMARY KEY (match_id, player_profile_id)
);

CREATE TABLE IF NOT EXISTS public.player_profiles
(
    id serial NOT NULL,
    full_name text COLLATE pg_catalog."default",
    country text COLLATE pg_catalog."default",
    sports_club text COLLATE pg_catalog."default",
    wins integer,
    losses integer,
    draws integer,
    CONSTRAINT player_profiles_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.requests
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    player_profile_id integer,
    approved_or_denied boolean,
    CONSTRAINT requests_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tournament
(
    id serial NOT NULL,
    title text COLLATE pg_catalog."default",
    format text COLLATE pg_catalog."default",
    match_format text COLLATE pg_catalog."default",
    prize integer,
    CONSTRAINT tournament_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tournament_participants
(
    tournament_id integer NOT NULL,
    player_profile_id integer NOT NULL,
    wins integer DEFAULT 0,
    losses integer DEFAULT 0,
    draws integer DEFAULT 0,
    points integer DEFAULT 0,
    CONSTRAINT tournament_participants_pkey PRIMARY KEY (tournament_id, player_profile_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    first_name text COLLATE pg_catalog."default",
    last_name text COLLATE pg_catalog."default",
    username text COLLATE pg_catalog."default",
    password text COLLATE pg_catalog."default",
    email text COLLATE pg_catalog."default",
    is_admin boolean DEFAULT false,
    is_director boolean DEFAULT false,
    player_profile_id integer,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.match
    ADD CONSTRAINT match_tournament_id_fkey FOREIGN KEY (tournament_id)
    REFERENCES public.tournament (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.match_participants
    ADD CONSTRAINT match_participants_match_id_fkey FOREIGN KEY (match_id)
    REFERENCES public.match (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.match_participants
    ADD CONSTRAINT match_participants_player_profile_id_fkey FOREIGN KEY (player_profile_id)
    REFERENCES public.player_profiles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.requests
    ADD CONSTRAINT requests_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tournament_participants
    ADD CONSTRAINT tournament_participants_player_profile_id_fkey FOREIGN KEY (player_profile_id)
    REFERENCES public.player_profiles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.tournament_participants
    ADD CONSTRAINT tournament_participants_tournament_id_fkey FOREIGN KEY (tournament_id)
    REFERENCES public.tournament (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT fk_user_player_profile FOREIGN KEY (player_profile_id)
    REFERENCES public.player_profiles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;